name: BACKEND CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
  
  jobs:
    backend-ci:

      runs-on: ubuntu-latest

      defaults:
        run: 
          working-directory: backend

      steps:
        #1 Checkout Repository
        - name: Checkout repository
          uses: actions/checkout@v4

        #2 Setup Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
            cach: npm
            cache-dependency-path: backend/packeage-lock.json

        # 3 Install dependecies
        - name: Install Dependecies
          run: npm ci

        #4 Run tests
        - name: Run tests
          run: npm test -- --runInBand

        #5 Build Docker image
        - name: Build Docker image
          run: docker build -t merchantflow-backend:ci .